### ISSUE TITLE
line 31 32

### ISSUE THREAD

**Issue by sec13b** [tinyboxvk/WPA2-Cracker#1]
Hello , can you explain Line 31 and 32 ?

what is exactly ? :  **"88023a019cb6d0fc90c77c8bcacbd7827c8bcacbd78200000000aaaa03000000888e0103005f02008a001000000000000000011a8b4e106c75287aa6d52dbc8342306e2f4f77e3826556a482bcd5f72c97e0f60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"**

    # Replace with your own values
    FRAME_1 = bytes.fromhex('88023a019cb6d0fc90c77c8bcacbd7827c8bcacbd78200000000aaaa03000000888e0103005f02008a001000000000000000011a8b4e106c75287aa6d52dbc8342306e2f4f77e3826556a482bcd5f72c97e0f60000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000')
    FRAME_2 = bytes.fromhex('88013a017c8bcacbd7829cb6d0fc90c77c8bcacbd78200000600aaaa03000000888e0103007502010a0000000000000000000103864225e34350a84df0061bb6ae60da4c0600879d50ec1ea4f47ee29da4b5da0000000000000000000000000000000000000000000000000000000000000000584c33e052eb53dd19001a339b42eefe001630140100000fac040100000fac040100000fac020000')

**Comment by tinyboxvk** [comment]
Those are the first and second frames during WPA2 key exchange in hex format. If you open a capture in Wireshark, you can right-click on the frame and choose "Copy ...as a Hex Stream".
